-- Migration: Add Agentic Blueprint Cache Support
-- Description: Adds caching column for storing generated agentic blueprints in the profiles table
-- Date: January 2025

-- Add agentic_blueprint_cache column to profiles table
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS agentic_blueprint_cache JSONB;

-- Add index for efficient querying of cached blueprints
CREATE INDEX IF NOT EXISTS idx_profiles_agentic_blueprint_cache 
ON profiles USING gin (agentic_blueprint_cache) 
WHERE agentic_blueprint_cache IS NOT NULL;

-- Add comment explaining the column purpose
COMMENT ON COLUMN profiles.agentic_blueprint_cache IS 
'Cached agentic AI blueprint data including business objective, digital team, human checkpoints, timeline, and KPI improvements. Generated by AI based on profile strategic initiatives and business goals.';

-- Verify the column was added successfully
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'profiles' 
        AND column_name = 'agentic_blueprint_cache'
    ) THEN
        RAISE NOTICE 'Successfully added agentic_blueprint_cache column to profiles table';
    ELSE
        RAISE EXCEPTION 'Failed to add agentic_blueprint_cache column to profiles table';
    END IF;
END $$; 